version: "3"
services:
  db:
    image: mongo
    container_name: talenty-mongo
    ports:
      - "27777:27777"
    environment:
      MONGO_INITDB_DATABASE: talenty
    volumes:
      - ./system_template.js:/docker-entrypoint-initdb.d/system_template.js
  backend:
    build: .
    container_name: talenty-backend
    ports:
      - "7800:7800"
  frontend:
    build: talenty
    container_name: talenty-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: https://api.talenty.duckdns.org
