version: "3"
services:
  db:
    image: mongo
    container_name: talenty-mongo
    environment:
      MONGO_INITDB_DATABASE: talenty
    volumes:
      - ./mongo.js:/docker-entrypoint-initdb.d/mongo.js
  backend:
    build: .
    container_name: talenty-backend
    ports:
      - "7800:7800"
  frontend:
    build: talenty
    container_name: talenty-frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://localhost:7800
