version: "3"
services:
  db:
    image: mongo
    container_name: talenty-mongo
    volumes:
    - ./mongo.js:/docker-entrypoint-initdb.d/mongo.js
  backend:
    build: .
    container_name: talenty-backend
    ports:
    - "7800:7800"
