server:
  port: 7800
spring:
  data:
    mongodb:
      database: talenty
      host: localhost
      port: 27777
  mail:
    host: smtp.gmail.com
    port: 587
    username: rafayel.shahnazaryan@gmail.com
    password: htgfjzcfzvdxanku
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

