server:
  port: 7800
  error:
    include-message: always
spring:
  data:
    mongodb:
      database: talenty
      host: talenty-mongo
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: rafayel.shahnazaryan@gmail.com
    password: qrypksgxvnoufdso
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: true