export const errorMessage = {
    EMAIL_ALREADY_REGISTERED: "Email alredy registred",
    INVALID_USER_NAME: "Incorrect user name",
    ACCOUNT_IS_NOT_VERIFIED: "Account is not verified",
    HR_ALREADY_REGISTERED: "Hr alrady regstered",
    INVALID_COMPANY_NAME: "Invald company name",
    INVALID_COUNTRY: "Invalid country name",
    INVALID_DATE: "Incorrect date",
    INVALID_EMAIL: "Incorrect email",
    INVALID_FIELD_LENGTH: "",
    INVALID_LOCATION: "Incorrect location",
    INVALID_PASSWORD: "Incorrect Password",
    INVALID_PERCENTAGE: "Incorrect percentage",
    INVALID_PHONE_NUMBER: "Incorrect phone namber",
    INVALID_SALARY: "Inavlid salary",
    INVALID_SECTION: "Inavlid Section",
    INVALID_URL: "Incorrect URL",
    JOB_SEEKER_ALREADY_REGISTERED: "This user registred",
    NO_SUCH_TEMPLATE: "No such template",
    PASSWORDS_DO_NOT_MATCH: "Password do not match",
    TOKEN_NOT_FOUND: "",
    USER_NOT_FOUND: "User not found",
    NO_SUCH_TYPE: "",
    GIVEN_TYPE_ALREADY_EXISTS: "Given type alredy exists",
    INVALID_TYPE_VALUES_LENGTH: "",
    INVALID_GENDER_TYPE: "Incorrect gender",
    INVALID_PROFESSIONAL_SKILL_TYPE: "Incorrect profesional skill",
    INVALID_PERSONAL_SKILL_TYPE: "Incorrect personal skill",
    INVALID_SALARY_TYPE: "Incorrect salary type",
    DUPLICATE_SECTION_NAME: "Տhis section already exists",
    INVALID_FIELD: "Invalid field",
    ERR_NETWORK_CHANGED: "bla bal",
}